[project]
name = "veryl_fpu"
version = "0.1.0"
[build]
source = "src"
target = { type = "directory", path = "target" }

[test]
simulator = "verilator"

[test.verilator]
#compile_args = [
#  "-Wno-UNOPTFLAT",
#  "-Wno-REALCVT",
#  "-Wno-SHORTREAL",
#  "-Wno-UNUSED",
#  "-Wno-WIDTHEXPAND",
#]
